### ISSUE TITLE
Add support of line-breaks in textarea content edition

### ISSUE THREAD

**Issue by balessan** [assemblee-virtuelle/wpldp#8] opened 2015-11-26 18:30 UTC
When editing a textarea form field content associated with a resource, the line-breaks previously entered are ignored on rendering..

Maybe this issue is more on the LDP-framework side.

**Comment by sylvainlb** [comment] 2015-11-27 00:10
Not a duplicate of #7 ?

**Comment by balessan** [comment] 2015-11-27 09:57
Is there a possibility that supporting markdown would solve the issue of properly handling the line breaks ?

I do not see the link there.

**Comment by sylvainlb** [comment] 2015-11-27 10:04
yes, markdown does support linebreaks. If you replace all textarea by components like pen, you won't have to deal with them anymore. Or else I'm missing something.

**Comment by balessan** [comment] 2015-11-27 10:06
You're probably right then.

Let's try to close the issue #7 and then check this one...

**Closed as completed** 2016-04-03 21:28 UTC
